// Word bank for Scribble It — organized by category and difficulty.
// The 18+ "After Dark" pack is opt-in, cheeky adult party material:
// innuendo, dating culture and nightlife, all still drawable.
module.exports = {
  classic: {
    easy: [
      "sun", "house", "tree", "star", "car", "ball", "cup", "hat", "door",
      "cloud", "moon", "book", "chair", "key", "kite", "clock", "candle",
      "boat", "shoe", "sock", "hand", "eye", "heart", "smile", "mountain",
      "bridge", "bed", "window", "flower", "gift", "bell", "island",
      "crown", "ring", "flag", "drum", "phone", "brush", "spoon", "beach",
    ],
    medium: [
      "castle", "rocket", "lighthouse", "rainbow", "guitar", "pirate",
      "wizard", "snowman", "balloon", "umbrella", "dragon", "mermaid",
      "campfire", "treasure", "volcano", "tornado", "astronaut", "windmill",
      "waterfall", "skeleton", "vampire", "scarecrow", "telescope", "anchor",
      "compass", "hourglass", "fountain", "carousel", "ferris wheel",
      "hot air balloon", "submarine", "igloo", "pyramid", "totem pole",
      "knight", "jester", "genie", "cyclops", "werewolf", "yeti", "phoenix",
    ],
    hard: [
      "illusion", "gravity", "echo", "shadow puppet", "daydream",
      "time machine", "labyrinth", "tightrope", "mirage", "deja vu",
      "constellation", "hypnosis", "camouflage", "stage fright", "domino effect",
      "writer's block", "butterfly effect", "wild goose chase", "cabin fever",
      "brainstorm", "culture shock", "chain reaction", "vicious cycle",
      "silver lining", "tip of the iceberg", "elephant in the room",
      "rose-tinted glasses", "house of cards", "double edged sword",
      "message in a bottle", "needle in a haystack", "eye of the storm",
      "second wind", "cold feet", "blind spot", "open secret",
      "breaking point", "fresh start", "last straw", "close call",
      "turning point", "clean slate", "white lie", "wild card",
    ],
  },

  food: {
    easy: [
      "pizza", "apple", "banana", "egg", "cheese", "bread", "cookie",
      "ice cream", "carrot", "cake", "corn", "lemon", "milk", "grapes",
      "orange", "pear", "cherry", "candy", "soup", "rice", "fries", "toast",
      "waffle", "hot dog", "pickle", "onion", "peanut", "muffin",
      "jam", "butter", "honey", "salt shaker", "tea cup", "coffee",
      "juice box", "ice pop", "pea pod", "tomato", "potato", "banana peel",
    ],
    medium: [
      "sushi", "taco", "spaghetti", "pancake", "popcorn", "watermelon",
      "hamburger", "pretzel", "donut", "pineapple", "sandwich", "strawberry",
      "avocado", "cupcake", "burrito", "noodles", "pumpkin pie", "milkshake",
      "bacon", "omelette", "salad bowl", "gingerbread man", "candy cane",
      "birthday cake", "coconut", "mango", "broccoli", "mushroom", "lollipop",
      "nachos", "quesadilla", "fried egg", "french toast", "bagel",
      "cheesecake", "pie slice", "soup bowl", "stir fry", "fruit salad",
      "hot sauce", "ice cream cone",
    ],
    hard: [
      "croissant", "fondue", "tiramisu", "dumpling", "guacamole", "lasagna",
      "barbecue", "smoothie", "meatball", "baguette", "escargot", "paella",
      "ramen bowl", "shish kebab", "creme brulee", "cotton candy",
      "banana split", "eggs benedict", "chocolate fountain", "cheese platter",
      "food truck", "buffet", "picnic basket", "leftovers", "midnight snack",
      "brunch", "food coma", "secret recipe",
      "sourdough starter", "wedding cake", "chocolate souffle",
      "sushi platter", "tapas", "charcuterie", "flambe",
      "molecular gastronomy", "pop up restaurant", "food critic",
      "all you can eat", "bottomless brunch",
    ],
  },

  animals: {
    easy: [
      "cat", "dog", "fish", "duck", "cow", "pig", "bird", "rabbit", "bee",
      "frog", "mouse", "horse", "snake", "sheep", "goat", "hen", "worm",
      "crab", "ant", "bat", "owl", "fox", "deer", "bear", "lion", "monkey",
      "chick", "puppy", "kitten", "swan", "goose", "moth", "snail shell",
      "tadpole", "pony", "donkey", "ladybug", "dragonfly",
    ],
    medium: [
      "penguin", "giraffe", "octopus", "kangaroo", "shark", "turtle",
      "elephant", "dolphin", "snail", "hedgehog", "flamingo", "butterfly",
      "peacock", "zebra", "camel", "koala", "panda", "raccoon", "squirrel",
      "beaver", "otter", "walrus", "seal", "parrot", "toucan", "ostrich",
      "starfish", "jellyfish", "spider web", "beehive", "bird nest",
      "polar bear", "rhino", "hippo", "crocodile", "gorilla", "wolf",
      "eagle", "falcon", "pufferfish", "coral reef", "swarm of bees",
      "anthill",
    ],
    hard: [
      "platypus", "axolotl", "narwhal", "sloth", "scorpion", "armadillo",
      "anteater", "chameleon", "seahorse", "porcupine", "lobster", "meerkat",
      "pangolin", "tapir", "lemur", "iguana", "praying mantis", "hummingbird",
      "woodpecker", "pelican", "vulture", "tarantula", "stingray",
      "hermit crab", "wildebeest", "orangutan", "capybara", "puffer fish",
      "komodo dragon", "manta ray", "okapi", "fennec fox", "snow leopard",
      "bald eagle", "emperor penguin", "blue whale", "electric eel",
      "leafcutter ant", "sea urchin", "basilisk lizard",
    ],
  },

  sports: {
    easy: [
      "soccer ball", "basketball", "swimming", "running", "jump rope",
      "bowling", "fishing", "boxing", "tennis", "golf", "skating", "cycling",
      "baseball", "football", "surfing", "diving", "hiking", "sledding",
      "skipping", "juggling", "yoga", "dancing", "climbing", "sprinting",
      "stretching", "push up", "sit up", "cartwheel", "piggyback",
      "arm wrestling",
    ],
    medium: [
      "skateboard", "archery", "karate", "hockey", "volleyball",
      "weightlifting", "cheerleader", "skiing", "wrestling", "darts",
      "badminton", "rowing", "sailing", "rock climbing", "snowboarding",
      "ping pong", "trampoline", "hurdles", "high jump", "scuba diving",
      "kayaking", "horse riding", "roller skating", "dodgeball",
      "handball", "water polo", "lacrosse", "curl bar", "shuttlecock",
      "goal post", "whistle", "stopwatch", "scoreboard", "team huddle",
      "warm up", "free throw",
    ],
    hard: [
      "pole vault", "curling", "fencing", "synchronized swimming", "marathon",
      "javelin", "gymnastics", "referee", "limbo", "tug of war", "zorbing",
      "triathlon", "bobsled", "shot put", "parkour", "bungee jumping",
      "skydiving", "paragliding", "sumo wrestling", "figure skating",
      "penalty kick", "slam dunk", "home run", "hat trick", "photo finish",
      "victory lap", "podium", "half time",
      "relay race", "steeplechase", "discus", "decathlon", "luge",
      "biathlon", "offside", "slam contest", "locker room", "mascot",
      "half pipe", "wipeout",
    ],
  },

  engineering: {
    easy: [
      "gear", "wrench", "hammer", "ladder", "magnet", "battery", "wheel",
      "screw", "robot", "antenna", "spring", "pulley", "nail", "bolt",
      "pipe", "switch", "plug", "lever", "chain", "ruler", "toolbox",
      "drill", "saw", "tape measure", "funnel", "pump", "fan blade",
      "light bulb", "wire", "pliers", "sandpaper", "bucket", "hinge",
    ],
    medium: [
      "circuit board", "blueprint", "bulldozer", "crane", "satellite",
      "microscope", "piston", "drone", "solar panel", "conveyor belt",
      "jackhammer", "periscope", "forklift", "excavator", "welding torch",
      "gearbox", "propeller", "turbine", "radar dish", "power line",
      "scaffolding", "hard hat", "blowtorch", "clamp", "engine",
      "pulley system", "robot arm", "printing press", "water wheel",
      "hydraulic jack", "cargo ship", "control panel", "servo motor",
      "gear train", "ball bearing", "sensor", "circuit",
    ],
    hard: [
      "suspension bridge", "hydraulic press", "transistor", "assembly line",
      "wind turbine", "3d printer", "jet engine", "pendulum", "catapult",
      "gyroscope", "particle accelerator", "soldering iron", "steam engine",
      "combustion chamber", "circuit breaker", "cooling tower", "dam spillway",
      "space elevator", "clean room", "prototype", "quality control",
      "reverse engineering", "load bearing wall", "tunnel boring machine",
      "nuclear reactor", "oil rig", "maglev train", "solar farm",
      "desalination plant", "rocket booster", "heat exchanger",
      "geodesic dome", "cantilever", "blast furnace", "conveyor sorter",
      "vacuum chamber",
    ],
  },

  adult: {
    easy: [
      "kiss", "wink", "flirt", "date night", "love letter", "lipstick",
      "crush", "slow dance", "hickey", "lingerie", "handcuffs", "hot tub",
      "champagne", "rose petals", "bubble bath", "candlelit dinner",
      "bedroom eyes", "thirst trap", "booty call", "sexting", "tan lines",
      "fishnets", "leather", "corset", "blindfold", "garter belt",
      "red lipstick", "stiletto heels", "silk sheets", "wine glass",
      "love bite", "slow undress", "shoulder kiss", "perfume",
      "mood lighting", "bare shoulder", "velvet rope", "whisper",
    ],
    medium: [
      "hangover", "skinny dipping", "bachelor party", "bachelorette party",
      "speed dating", "blind date", "honeymoon suite", "pickup line",
      "netflix and chill", "friends with benefits", "one-night stand",
      "situationship", "lap dance", "pole dancing", "male stripper",
      "body shot", "strip poker", "truth or dare", "spin the bottle",
      "seven minutes in heaven", "massage oil", "whipped cream", "ice cube",
      "do not disturb", "hotel key", "back seat", "motel", "wingman",
      "dm slide", "left on read", "ghosting", "rebound", "drunk dial",
    ],
    hard: [
      "walk of shame", "midlife crisis", "gold digger", "sugar daddy",
      "cougar", "silver fox", "dad bod", "mile high club", "second base",
      "hall pass", "open relationship", "swingers", "safe word", "role play",
      "red light district", "morning after", "commitment issues",
      "awkward first date", "ex text", "love triangle", "matchmaker",
      "cold shower", "body paint", "striptease", "champagne shower",
      "slow burn", "shower for two", "bikini wax", "morning breath",
      "third wheel", "kiss and tell", "little black book",
    ],
  },
};
